<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use DB;
// use Faker\Factory as Faker;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $faker = Faker::create();
        //https://yulvil.github.io/gopherjs/02/
        DB::table('teams')->insert([
            'name' => 'superadmin',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        DB::table('teams')->insert([
            'name' => 'gerente',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        DB::table('teams')->insert([
            'name' => 'supervisor_camal',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        DB::table('teams')->insert([
            'name' => 'operario_camal',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);
        DB::table('teams')->insert([
            'name' => 'administrador_camal',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        DB::table('teams')->insert([
            'name' => 'supervisor_mercado',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        DB::table('teams')->insert([
            'name' => 'operario_mercado',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);
        DB::table('teams')->insert([
            'name' => 'cliente_camal',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        DB::table('teams')->insert([
            'name' => 'veterinario',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);
        DB::table('teams')->insert([
            'name' => 'usuario-mercado',
            'user_id' => 1,
            'personal_team' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]); 
        DB::table('users')->insert([
            'cedula' => '10039698542',
            'name' => '10039698542',
            'current_team_id' => 1,
            'nombres' => "Juan Marcelo",
            'apellidos' => "Perez Liztor",
            'telefono' => "0959072238",
            'direccion' => "Quito",
            'foto' => 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXDa/X9X3GcU89lllaRHfA4XB07SqESZWqVdetHmPEMTotdptJSdU6FTNro5UoykxGVZxzgjfYMR1ZtXFVsdqqOCetOLzBdsJmiybMUQcWhRW0BSeEDdijuJIl1+v1AK7vye/kn3c+gxd/87IDko7e90B0/81bJ0f3lx9/SnT/sx9fGt1/cv4Z0f1nvnB1dP/sK2ZG949Y+x/R/eNfG4ruz1gZnT/g4XsXRfdHXftKdP+4YzZF96deenJ0f8Pd70T3PxBdB+D/LQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUGrg5+Mujz5w0NeOiO5PX/v30f2d634R3f/pmX8Q3V+8aGl0f/qkUdH9sctWRPfHH/l70f3tGw6N7j/1yKzo/g+PfSi6//Sib0b3Tzjo0ej+wXcsjO5v2jc6uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDSwc/Xj0gdVz3o/uf/DiCdH9oXefiu4/vmNcdP+Yu0ZE93e9vDa6//yf7Y7u/2zsa9H9q+4dH91/e/O06P53Hzw9uv+tVYdF9//h678W3V99zEXR/d8YuT267wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNfGLL0ugDt2x+LLp//IVPRPfn3vhwdP8rb/9xdP/4aRdF939lw7nR/bcunBXdP2HHx6P7G09dFN3/8fA90f3x806N7j+z4rro/pg186P7i1/9ZHT/yUuGo/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MAjH50YfeCwRydH989/bjC6v+CiK6P7hy6bF93fdnb2+39+7K7o/opvLY7u77zyvOj+qHXXR/cPXnJidH//KVui++P/+vno/v+cdUh0f+JRT0f3n13yo+i+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDWwe/iC6AOzdx0a3f/LzX8a3b/x9rOj+0ef9lJ0f8m3H4nuP/vCVdH9Czb+U3R/wtZDovvX3nd3dP9rD14W3b9m4o3R/eH/nB3dHzzwI9H96+dcGt3fM/Tl6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNfDpQ4ajD1z/wI7o/txXPxrdP2fSlOj+ibdfEt3/2JdXRfdvnjEuuv8vZ0XnD1hy9BXR/VU7j4ruP/LK1uj+2vdHR/cXHDsrur/3quz3ue772e8zMGpldN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGvzCuKeiD5xw27XR/ZcumRrdH95+RHR//GnZBv/hnInR/V/8+pXR/Zmrdkf3X972oej+3Me3RPe/P3h/dP+a0w+P7u+4Ifv7PWv9yOj+SW/+W3R/8X9/OLrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg0unnxb9IFxm+6M7v/Ju3uj+7ufejG6/5NPz47ur7rtr6L7G9YcFt3/+T9Pje4/+alN0f355z8f3Z+58ILo/m8PnhTdf/mZbdH9w3euiO7vGrMnuj90yNzovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg1cM6kL0YfuHfGmdH9m+eNjO4fPWlWdP+coUXR/Ue3Xhfdf2xv9v+78KFPRPf//eEjo/vL57wa3X/4pnnR/W2/OSW6v+edydH99/Y8F92/58DXo/ufe25bdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGhxz+J9HH3hnywvR/REb74juf2XBV6P79y372+j+i0PnRfefuPyg6P6XFgxE94dv+mF0/4uXvhbdP+6u06P7/zvzzuj+iH89Lrr/X4PXRPenfSP7998067ei+y4AgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKDUwGfWfDj6wLabpkb3vzHy5uj+ml99MLq/5JmjovuT798c3d839uno/knvXR3df/nAMdH9q5cviO7funxZdH/NlHuj+3tXPBbdP/XsM6P7b0w4P7o/8rF10X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQanDqkQujD5x82Eei+6ee/Hx0f/3Mi6P7w7tWR/e/M3VrdP/gH1wW3f/qsyOi+0tfuiW6f8sH5kf3H1o/I7q/+twHovtT3jsjur98+vei+7f+7NDo/t8tnR7ddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGvjtiSvSBd59cEN2fM/qy6P60uWOi+zfuWhndHxqeFt0/7cDzovsnXn5GdP+KUW9F93/5j7dG9+9Z/zfR/dHXTYruT/veZ6P7r3/sd6L7d63bH92f8NPPRfddAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAqYG7bz4h+sDbQ6ui+y9cujy6f/DoedH9ja/dF93/4OMHRfc/dOyF0f3bvzMuuj/rqhui+2NP+0F0/8cz7o/uv/j6K9H9T76/Mro/+4Z10f2hCT+J7v/F7++P7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSg58/5c7oAwvPmR7d/9SLE6L7D765Lrq/97iV0f3fnX9sdP9Hq46I7j+x/dro/r5l347u/9HsX0b333pjQXT/3NVfiu6v/fo10f0jJ2Z/v3e8sTW6v/8zq6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNT/BQAA///w235Cq7mdYwAAAABJRU5ErkJggg==',
            'fototype' => 'png',
            'estado' => 0,
            'email' => "superadmin@hotmail.com",
            'password' => bcrypt('12345678'),
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]); 
      /*   DB::table('users')->insert([
            'cedula' => '1000806321',
            'name' => '1000806321',
            'current_team_id' => 2,
            'nombres' => "David Leo",
            'apellidos' => "Quelal Rosero",
            'telefono' => "08799555412",
            'direccion' => "Ibarra",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXjdcXdH3G8e7t1k5j+JAuwRxghC4x52Q53Y6TYRKwhU9DD2DLzRq62VL0mIsks6mL1ZG1DVajLILcQluM8SDTiHIdhExi8VABpxTGQVg+sNODIOyvuM7ZOdfr9Qdc3/vc9+93v89n8L6fD39N0tdvODW6/+OBydH9u/5mR3T/d8evje5/bOzHo/s/WvJqdH/xP3wsun/FU1dG96973aXR/Ys2fTG6v3POjdH9vQtXR/e/PXJXdP+j93w+uv/xebOi+78QXQfg/y0BACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqcPWtvx994MLZP43ub1x4dXR/9N6TovvPLp8R3d808+bo/vU/GRfdv2fhk9H90T88Jbu/+GvR/bdcOzO6P+OXs/8f5j01Mrr/hZ9ti+6vOutd0f1lX50b3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBiee+/3oA2/e+q3o/nOT5kb3Jz75QnT/ll8ZE92ffvRwdP8Dnzkluv+bdz8c3Z/30eznZ8mKz0f3d/139vs795xR0f35p06N7m/48a3R/e/MHRbdf2nwaHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBr8wZEzow8MPelgdH/romnR/Rlv3hTdX/jepdH9r455W3T/4tNeG92/5XW7o/vLXngpuv/9s7ZH94+fOTW6/+El34zuf2r25uj+r5+yMLp/+kXfju6vvfN70X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQavCH+9dEH5g5bHt0/7gRb4ruD/zdlOj+8PH/E92/7N7bo/tnTh2M7t+0O/v52f3lM6L7d37376P7+y99ILo/5fanovvD7hsV3d+7dVN0f8/w06P7N4/Kfj5dAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAqYE/2rs8+sCF+x6L7k8+PD26f+u986P7y975lej+ba85K7p/3IK3RPef3H9ydH/jCb8W3R939rHo/uDaX4ru73v0iej+gxM+Hd2fd9qQ6P4jh3ZF93fO+kZ03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQa3DP3gugD1/58Y3T/4j89Prr/oWn3RvdfuHRxdP+hYSOi+986aUN0f9ZFF0f3x6y/Nro/7sv/HN3/6397X3R/9eG/je4fu/uJ6P7my6+P7k89uDS6P/bxZ6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTAVa9mG/CJoZ+N7t+xbVV0/9BZK6P7I06/Kbo/fsV10f3512yJ7m+c/mB0/8+H/jS6/8Sic6P7Tz9+eXR/zz9dGd3/wU1ro/sPnjQ2un9w5eTo/pKHr4/uuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFIDI3b9YvSBq3Yeje4PuejF6P7Fjzwf3d+577zo/v1r1kf3p419f3R/wobF0f0zrrg6uv+hyy6J7j/68I3R/UPLx0f3V7/rmuj+yDdsi+6PnXhVdH/OZ16K7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSA/8x+k+iD9w8fXx0/4ILJkT3Nz19eXT/0Y+cE93/qwPjovtv/eCB6P6kx/41uv/2t14S3T/vvO9G98+9a150f9WMn0T3N40+Ft2ftOC86P4n738luv97Lz4Q3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBsa8d230gad37YruXznhlej+sS9dHt0fctea6P6yZ86I7h9Y83x0f8HUodH9K0a8M7r/7O9sjO7fMetXo/v/++Jx0f0PPPuR6P6QI2dH92+beEp0f8m/HInuuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFIDJ05bEn3gD0+8Ibr/yF1Dovv33Lsnuv/bb8v+/Nf9xezo/tdOmxDdP7rxlej+lP/cF90fdce66P6ElSOj+1c8kP39r3n/8Oj+H3/4guj+m7Zsje6ffMOD0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauDA9lnRB7ZdemF0/7Ijc6L7E7f+ZXR/xHNLo/sH7zsc3Z8/5fro/qGJC6P7q4d8J7p/zrj/iu4PfO4fo/u37Lgkuv9bQ7dH9/cPPhTdf/vVG6L7U595d3TfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBo8d+qnow98afDl6P7yT6yK7q/bMjm6f/u63dH9QxNHRfd/NP3U6P6hs98R3X919JnR/R2Tronuz5mU/f7OGnphdP+TN82K7m9flf37vjxjQXT/hLEro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MDsKVuiDyz94ubo/uyHFkb33zf/quj+92b+RnT/xncMi+7/wdnvie7vXPT16P431m+P7o+9+87o/sEjk6L7K3b8e3T/K/PfGN0/YdT66P61bxwe3f/ZonXRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqYM57no8+8M3RB6L7L588Lbr/+Gs/Fd0fuWpFdH/I6/8sun/+5+6J7r/7scnR/eNnvD66v/n826L7i+/fF92/ZdKw6P6yMWui+6ue+2B0/w2fPTG6/4WZ50f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKn/CwAA//9Cpn/lG2Z2LwAAAABJRU5ErkJggg==",
            'fototype' => 'png',
            'estado' => 0,
            'codigo'=>'PSEP-1',
            'email' => "gerente@hotmail.com",
            'password' => bcrypt('12345678'),
          'created_at' => '2021-01-04 11:14:53',
        ]);
        DB::table('users')->insert([
            'cedula' => '1003338520',
            'name' => 'C1003338520',
            'current_team_id' => 3,
            'nombres' => "Paul Libo",
            'apellidos' => "Córdova Quinchiguango",
            'direccion' => "Ibarra",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHElEQVR4nOzXj9fXdX3GcRi327RScToSxDyi6DFPR52CqPdhjBZnGiNEK00Uszw2C93kbGdJdcTV2JkeyqZsLVuEsUmiASu0/MEcJ5iEZFbgwRYMWVsYIjBPinDvr7jO6Zzr8fgDrvc59/l87+d5DXxu1OphSYvvnB/d/9Z/rYrun3/DJdH9wQP3RfcHVv9GdP+x0Zui+/+6aml0f+YtN0X3j5k5FN0/6uSLo/vPfuXF6P76Rc9F97ddOC+6/6NvLozuj7vxheh+9r8DAL+2BACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAqeGrD/44+sCW0a9E91cOmxjdn7TnnOj+h1/6dHT/8VM3RPefXXNsdH/9bWOi+5+ZPCG6f+YvdkX3/2LW2dH9sSNmRPc/vyH7fR5x5xei+1/784ui+0+v3xnddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGNn5ldvSBTX85Ibo/Zc+90f05H/1sdP/gvmOi+zu++EZ0/zsTroruXzl4WnT/+7eOj+5fuuyD0f2Vg5dF93/x7Pro/v3fnh/dXzP9bdH9m8/aHt1fsndXdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGpixd3H0gVuvmxLd/9WOJ6L7dy//QXR/87H7ovsbr7syuj/s4onR+WnH/1Z0f++NR0b3fzn9rdH94066Lbp/+oL90f2rTlwQ3T/97dnvf8Ejp0T3N1/+1ei+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDXw9OmnRB9Ycvam6P6nZ8yI7q8YdmN0f8r9T0b3x45bGt0/dun+6P6D/zM1uj94zEnR/XOfeSi6P+2E6dH90Wdkv5/t5/xZdP+vF38yuj80+VB0/32zz4nuuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFLD5112QfSBb5w1Kbp/wmOfiO7P++7a6P7hdbOj+/sO/Ft0/4iXxkT3Hz/uV9H90VfujO5PGByK7v/m+7ZE9//jh0dG9ycdmhLd/8ef3xfdf2Tq/Oj+3B+fEt13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQaO+sED0Qcem3dtdP+sZbui+4f/4FB0f8y656L794x6e3T/J+PmRvc/v3BldH/qQ9m/z/gRO6P7R496Nbp/xr2XRvcXjXwhun/k370R3V80Z0t0//lly6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTAplFrow9c89T26P5dO2ZF91e88mZ0f9vUW6L7X90UnR/2/KdGRPeP2v9wdP+i+y+J7v/Jl1dH91f/1YTo/mdXbIvuP/xi9vvZfcYd0f0nT/rj6P6Bbw9E910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECp4aceHBN94D0/XxTdX7Xxkej+zgXrovuPL98a3f/3W38/un/T4U3R/ZevHhvdn3TOnOj+2Nd3R/fvvn15dP/6d6yM7o8/Mfv7fe892d/X5lPfFd0/cNMHovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MCXf+93og/sem1PdH/Elz4e3d++Y1N0/4lzR0T3Zyz9UHT/jY9E54dNu2xidP+PPvyl6P6k762I7t+39uro/uDB06L7v33bwej+wKtjovtfm/BodH/jgsXRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq+EcueTT6wD89ty66f+/nronuXzBwTHT/uj0fjO5POPfC6P7gyzui+/tnjo3uv3z5vOj+PXc9EN1/8/vjovu/e8GN0f2Lb58d3f/p5qHo/oF3vyW6v/uqKdF9FwBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUGrg/efPjD6w4bsjo/uz538run/0Ne+P7n9o/rHR/emXb4/uD95wVHR/9JHLo/sfuyK7/8lL3h3dP23UP0f3l4y+K7r/lmlD0f2DQwui+xs+8Zno/h9ueVt03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQavvWpJdEH9l+9Pbq/6qx3RfeH7jgvun/82Qui+1cMTYvuz5z6k+j+wMjro/tHL/xZdP/C+xdG9z/wjdOj+9MffDS6f/X/fSG6P/euh6L728c8H93/+gXZv48LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNTBu7djoAy/Mmhzd3/apv4nur3nmhOj+qw/vju5/8ZnvRPfHbx0Z3T+8e2t0f8X5m6P7H7/+huj+67N2Rvcn7p0R3X9g5Kzo/n8ef2d0/5VRL0X3r521IbrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg2cfNw7ow/csu+86P6aJ3ZF908e847o/qGdW6L7e0+4Jrr/909nv5+nFr8nun/Tkz+K7n/0Z7dF9z928onR/bn/cmV0/4wjZkX3v/nfc6P7885bE92fs+GX0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQavi+966KPnD3a6dE96+4eU50/6rJI6L7d1w6Lrq/8MwXo/tv/d8zo/vrJ74Z3f/hogej+3eP/2l0/x9uPjG6//XX/jS7v+TC6P47L/pedH/ytbdH91e8/rfRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFDq/wMAAP//zf+BUg/CgkYAAAAASUVORK5CYII=",
            'fototype' => 'png',
            'estado' => 0,
            'codigo'=>'PSEP-2',
            'email' => "supervisor@hotmail.com",
            'password' => bcrypt('12345678'),
            'created_at' => '2021-01-04 11:14:54',
          'created_at' => '2021-01-04 11:14:54',
        ]);
        DB::table('users')->insert([
            'cedula' => '1003453741',
            'name' => 'C1003453741',
            'current_team_id' => 4,
            'nombres' => "Andres Pablo",
            'apellidos' => "Perez Querembas",
            'telefono' => "09526577955",
            'direccion' => "Ibarra",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANH0lEQVR4nOzXjdcWdH3Hce+6NcWVOqQyJZWDns5UHIpamKcH7UFkzJj4dEoET9o0Gx0SE8fgoAkj2+xMtAUtIiTS1lptPiRsnuUYCOEED3ngTLFDMyBU5ppQIPsrPud0zuf1+gM+v3Ou+77O+/oOfnnJnkOSZq99Mbr/4sj90f2dzw2P7k++6Yro/u6hS6L7A+99c3R/31lTo/u/fOjl6P7//t7k6P6Z1301uv+Nh86O7r/r6rdF9zef85bo/qz7fhjdf3LOmuj+m6LrAPzOEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQbeesZA9IGNj98R3f/A3edH96dP+HB0/9iRY6L7i1feEN3/0H9cGd3/5pbTovuf2bIiur9mxYPR/XlTfxTd/9fDFkf3l2z4dHT/lAMXR/fnPH1cdH/BuBHRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq8JVRR0UfmPvj66P7p+4eGd2f+NMvRPevv/2k6P7UTVui+58Yc1Z0f8+iddH9MT97OLr/8RFnRPcn7f11dP+2D54Z3d+649+i+8MP/UV0f9PPb4juX/DEqui+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDUw78I7og+MHf+L6P7sK5+J7s996c7o/oib50X3z/3lD6P75638bXT/jOvWR/ffcXL28z/ss5Oj+8+/vjq6P/6BzdH9r79tWHT/ix99JLr/zW3rovsHV/1ddN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGhx/xZHRB56/6tbo/sDc0dH9YQ9/Orr/9786Irp/xC27ovsnvH1+dP/o46dE99+x5aTo/r3vOTa6/52lE6L7a9+9MLp/69V3R/cvWzU3uv/jUY9G94cO/6PovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg1+Nebd0cfWPPtFdH9tw7ZEd1fNfFn0f0NG66P7o/c82J0f/kJt0X3l/38qOj+nkXzo/tjT/jH6P6pU9dG98fPPTS6f+3+ddH9Px19X3T/iFsmR/fvn7Y6uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDYyaOS36wG2PnhLdn/W1hdH9P1t+f3T/D286Mbr/qbd8P7p/86nfiO5fM+190f2t730tuv9/BxZE9x//0Nbo/jOjo/OHrL1+ZXT/5qOOie6vOSz7G3rnikui+y4AgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKDU4KZ7tkUfmLb8A9H9S2Z9J7r/uef+K7r/63dOie6/NOz06P6QS6+N7h+3Y0Z0//ZDV0f3J974WnT/+WXjo/tjz/tVdH/+g8Oj++c++1fR/dXPTIjuH3li9je6CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDU474k50Qd2feuU6P6Tl30mur/9qrOj++/c8Wp0f+llC6L752xbGt1/05bp0f2592yN7h938qLo/uIxU6L7D5x9cnT/b9atj+6P+8je6P5Lc7Kfz9U3nRfddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGNr79qegDE4d/Lbq/f/BgdH/X4WdG938wd3t0/8t/OSG6f+unXojuj3js8uj+sgtHRffvXbYvun/dluz//8A5O6P7Rw57c3T/tRnnRvenz7w6uv8vS06L7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSg7svPir6wF1DLonujxv7eHR//3PXRvdPvHRodH/G6adH93c8/KXo/oHf/Hd0f9VFD0X3j/7n34/ub5+3MLo//2N7ovvbv7o0uv/Zg3dH9z/59P3R/Y/v3hzddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGz39sb/SB7Quvie7vfP390f3DV26M7o9aNym6Pzh4YXR/6Bv3Rvf3XHQguj/zD6ZH98+44o3o/uF3Zv++1/xD9jfiE4M7o/tr950W3f/8F2+M7q8/+oXovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg1+PrNW6MPPHj83uj+pevPje6vufM/o/t/POT86P60bZOj+0NGz4juTzzr5ej+nlumR/fvOeYT0f1Z785+vyZP+0h0f/O4w6L7j3x4fHT/qc9dHN1fO3RqdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGjhzws7oA58c/aPo/rMTj43uf2X+zOj+qbPGRfefXffd6P6mjTui+9971wXR/R+MGBPd//cbL4/ub/zbV6P7w/5kV3T/J1Puiu6PPGZOdP/R0VdE938y9vvRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqcMH4adEHdj15eHR/0SvTo/sfO+R/ovv/dNGx0f1XTnp/dH/rX0yK7o+9amV0f/mVo6P7M0/Jfj6bH3squj/7vm9H99/47Yro/ubZU6L7X7g9+/29/IJt0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauDSSaOiD3zr6w9E99ePuSy6/5479kX3n/7KmOj+zu+tie4fv/Cn0f0NU2dG939zw+ej++MmPRLdf3nxEdH9L+24K7r/woqTo/uvfveD0f2LProquv++g38e3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAACl/j8AAP//7Ax/8QQ5VPwAAAAASUVORK5CYII=",
            'fototype' => 'png',
            'estado' => 0,
            'codigo'=>'PSEP-3',
            'email' => "operario@hotmail.com",
            'estado' => 0,
            'password' => bcrypt('12345678'),
            'created_at' => '2021-01-04 11:14:55',
          'created_at' => '2021-01-04 11:14:55',
        ]);

        DB::table('users')->insert([
            'cedula' => '1001421617',
            'nombres' => "Maria Ana",
            'current_team_id' => 5,
            'name' => 'C1001421617',
            'apellidos' => "Angulo Pelambre",
            'telefono' => "09526577445",
            'direccion' => "Ibarra",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANIElEQVR4nOzXDa8edH3GcQ4cmiMijIfVbTCFrqWOZgXhEJmBdVBgUNu1QkjpkQeHRZ50IqtOHgoeJ7BCMs2GlKGA2q0obJ2xlW3Sjmydk7HSoyJwrFoylNa2Al1p67RwtldxJSbX5/MCrn9yzn3f3/wGL33Dwv2Svrr6jOj+B8bfGt3fN+f66P62CzdG939zzpnR/evGVkT3f/S98ej++KqLovvLFq2M7v/Xl66M7p/7mU9E90cP3xPdX/LfL0f3T/j5kdH922buiO7vH10H4JeWAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNfDOnT+IPrBz5TXR/T1/uiC6f9ADG6L7o39yV3T/kt96a3T/LxbPi+7PO/Kc7P6xr0b3n104HN1fsOCz0f27Dnkouj9r5F3R/a2fPzG6/9Kd343uv2Pjkui+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDX45Jpjog8cO+/g6P5+s3dH57cNTY7uT133tej+ve89L7r/d1v3RPdPfvb46P4jt10a3T/1jkXR/dOGnojub/3MidH9Q771yej+wDk3RPdXL1wd3d8+MBzddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGbxn5negDx31zZnT/iGOnRPc//eAt0f1NM/8hun/Y0CXR/TkfXhXdHznvc9H9yTfeG92/ddOvRveXnHBDdP+nk0aj+y+/dEh0/983/Cy6f9AJk6P7D047NbrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg0O3f2h6APnnj8a3V/0xv+J7p9/wOTo/rr3fT26f830ddH9U/b9S3T/sW3Zz8+RV1wd3f/S67dF929ec0t0/877jo/uf+8PPhDdv2LWw9H9s8aej+6/beL26L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNTD/UzOjD9z3luXR/f1/eFx0/7rD/jW6P/rYouj+VU/dHN3/+fS50f0/3HxpdP/Nd4xG9997+f9G92+9YWt0/4wfzY/u3zP87ej+Dy7I/j7se/7t0f3D9/tmdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGjj56cejD+w67AvR/Q2vXhzdP2roPdH9WUedE92/84lno/u7FmyN7k98fG90f/7j66L74w8vjO7/8MKl0f3hz94e3T/2wKnR/Y/++WHR/Quuvyq6v/Zj90f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmBvbsOjz7w5PL10f1pD54b3X/678+I7l//GwdE97ee9Ino/pknronuf/2m70T3Z7+4Mbo//dDJ0f0V//SG6P7iGcuj+7etH4nuX3zXYHR/5TNLo/v/8ba50X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauC5Lb8WfeCPrngkur9917To/pvGPh7d/+hjX8nur5wU3d85/K7o/tqhg6P7l679bnT/b886K7p//NqLo/unnLgkur98YiS6f+Ob10b357xyf3T/G5ffGt13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQavu/a16AP7Phmd3++dV45F978z+xvR/aO+PR7dP/vkF6L7G6dPju5PHPJQdH/431ZE92dPmRHdf/HtJ0X377npa9H990+fH92fcdqt0f2lX7w9ur/6+3uj+y4AgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKDUwMgLL0Yf+Odnfj26v/KR56L7p0/ZHd2fNfPq6P7DSyZF94e2/SK6//7Lroruv/A3vxvdP+2h86P7L1/y4+j+F366Kbr/vrFTovuPHrQ4un/04oej+3t+PBHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGZzyzKfrAlXunRvfH18+L7p/+szdF9z9y+gXR/btX3xvdP3Pdiuj+0D3TovsnHPh4dP/y5zZE9+ef/eno/nvG74zuP/2p7Pdr1f3HRfenH/zX0f11358U3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBubumYg+cMeMU6P7r2+8Obo/46k10f3hIz4W3b95yZbo/pTRY6L7R3z4vuj+h5Y9Gd2f8+ih0f29Sy+L7n9lfHd0f3Rv9v87PPur0f2Hxh6J7h+9fkp03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQaWLthRvSBDasvi+6/um5FdP+Ya5+I7n951ubo/vMjN0T3f/K5udH9P1uf/fvsmHJTdH/F9Tuj++/4v7uj+1cvOCW6v+y1B6L7V/5kanR/56E3Rvf/ePl50X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauCgpc9EH5h3zBuj+7t+5fPR/WtH10T3J41MRPd3/OMr0f0PvjI/un/19rOj+1PPfjS6f+T+L0X3Lzzvt6P7B4wdHd3//UUj0f2zRlZF92ee9MXo/tjA2ui+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDX47h0fiT6wedXvRfcvXrY1uv/aRfOj+1/evDG6v2XeL6L7k7c8EN1/atO3ovvHL353dH/ZNauj+wvn7o7u/+dfToruv2Xo9uj+By+5KLp/4MRfRfcfmLY9uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABK/X8AAAD//xjQf7oSEHF7AAAAAElFTkSuQmCC",
            'fototype' => 'png',
            'estado' => 0,
            'codigo'=>'PSEP-4',
            'email' => "admin_camal@hotmail.com",
            'password' => bcrypt('12345678'),
            'created_at' => '2021-01-04 11:14:56',
            'created_at' => '2021-01-04 11:14:56',
        ]);

        DB::table('users')->insert([
            'cedula' => '1005577382',
            'name' => 'M1005577382',
            'current_team_id' => 6,
            'nombres' => "Piter Mateo",
            'apellidos' => "Matango Palomares",
            'telefono' => "095265755",
            'direccion' => "Ibarra",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHUlEQVR4nOzXj9fXdX3GcW+7PaI2EadOozb0nqsYSxk4U0msSaI0B/2QqQP12GbH6mhHp810SUY6T002qJMrcXmK0pBaRpGTBnMSYGw1txsoggmFYIXGITAS2F9xnbNzrsfjD7je53zP93Oe5zX4/d0zD0u64rRzo/vbl2yL7u+8YUl0f96csdH9VX/whuj+uuMXRPcPHzo8uj/jJ++J7r926ero/nkj7onuX71lOLp/142jovvT/m1hdH/q2Zui+y/+6AfR/ezXBcD/WwIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTAK+Zsjz4wf/qO6P6Je8dG9yeO2BLdnzb6muj+is9Nj+6/+O3PR/cXvm1SdH/ZWddH92ef8OHo/hnLJ0T33zfjyOj+gYNLo/uHv3BmdP+H678R3V98xAPRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqYMSZ740+cNfocdH923+yL7q/bvq26P6B3RdF9//jjOj8YdP/9/ej+wenrIruzz5me3R/zw+z39ehZTui+2svvyu6P+Xtx0f3r/7O0dH9Fy//anT/0skro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODjL18WfWDhqd+M7k/+2DXR/bkzPhjdHz7pt6L7v/vZn0b3Lzn6huj+P564ILp/2d7J0f13Tloa3X/rK5+L7s88b1Z0f//KM6P7rx5aFN0f98K66P7Hr/+r6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNXjDJQPRB648ZV50/wsb/ye6f+qu10X3Nzy/O7q/7qo7o/vvWnhfdH/szNXR/R89viK6f/DN50b3R166Lro/6+8XRfeHbz4iun/f+4+J7k+9c2t0/8dfejK67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNHrfsv6IP3HPxluj+3DWXR/efu2Uwun/Noezvc/KXN0X3z/ib66L7B44eF90/9K2To/sbRl0b3T9v7CPR/c9c9IXo/k2fzf4+D53/5uj+b778VHT/+dOHovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1OAn3nJr9IHvPb8zuj/0pR9E9685YlZ0/00f/ufo/obh/dH9Z4dHRPfff+HT0f337F8Z3R916/To/n8vOiq6f/Ovp0b3L3zNk9H9NX+yJbr/yg+cEN0/f+qU6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNfDAmnujD8y67Kbo/iPfe1V0/+yPHh3df+jdQ9H963+9LLq/e8nT0f2L7/5pdP/A/Duj+1+f+2h0f9nt10X3PzV7dHR/xbzV0f1df/zz6P6ze2dF92+a+IHovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg18J9/ejD6wL8vye4/cdKV0f3v37Inuj/1jjnR/dMuvDi6f8LgUHR/3Fm/F90fNfql6P6UCQei+9MmvSa6v/WlidH9X8zP7l93/+9E9x/9yCej+0/uuDe67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN3HLY3OgDI15/f3T/b29dG91ftO+C6P5f73swuv+q25+I7n934m9H91fNz/5/zpz81ej+jU99Lbq/es/m6P7Uncuj+2M+8avo/vRvXhHdH/m+j0X3x393TnTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBo4+Q0jow/sm3pjdH/050+L7r/uyqOi+xe95eno/t5l50f3B8beF91fcPDI6P68f/pZdP+FR2ZH9//y1LnR/Snj90T3x++6Krp/+rHLo/srLronuv+Vd6yK7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSg7+acFz0gc23XRrdH750OLr/zIavRfc33XFidH/rx/dE9xce2hTdf+2Ch6P7m++dGd2/5LgV0f0vPpj9f77rjguj+6//4KLo/ubbzonuP/zu9dH9HcuHovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MBDKzdGH/jI5Oz+p9f+Mrp/7u0zo/srF38oun/K+H+J7i9esDS6v/+Kz0X37/7QP0T3D4x5Krr/85fXRvefPfRH0f2T9p4d3R/zxiOj+0cdtzW6P/KYj0b3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnB+9eeHn3g+OGR0f1jFz8W3V+4/hXR/R8/tjG6/9K9x0f37371L6L7X/ny+Oj+e8dMiu6PmvBodP+Wq5dE9x94x67o/s2rvx3d/4tZi6L737lgRnR/67Rl0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauDmSfdEH9h266zo/lnvPBjd/43Lrovur3x4T3T/iVWPRfeX/+EF0f1PXfvn0f3xM56L7n/9qm9F98fMvju6P/aX2f1x1w5F94ffvj66v3TpudH989dMi+67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgOfvOOU6AOfefCt0f2frV4f3d9y8nnR/Y3bj4zuX3zO26L7V02YGN0/duno6P5tWzdG99fv/LPo/r+O/WJ0//Jtj0f3z3nmjdH9N/3dnOj+4MxPR/ef+caB6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAo9X8BAAD//6fuiTsDkSyLAAAAAElFTkSuQmCC",
            'fototype' => 'png',
            'estado' => 0,
            'email' => "supervisor_mercado@hotmail.com",
            'password' => bcrypt('12345678'),
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('users')->insert([
            'cedula' => '1005577382',
            'name' => 'M1005577382',
            'current_team_id' => 7,
            'nombres' => "Xavier Mauricio",
            'apellidos' => "Roland Pajares",
            'telefono' => "095265755",
            'direccion' => "Quito",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXi6/fdX3HcU57mFTZmNzSOooMLTIQBE4hXMpldbhpuWxokbIKiiU4OT1SoWDDgK1MHShjRWiVpCUUaCM6B7Wo1VIVsJcAKbJ1WCibhbXFxpqVKh1NNfsrXsmS1+PxB7w+yS/f/J55D97yrl37JH3uy/dH939x+ubo/ujPHBTdP377tOj+3teOi+4/vO93o/sPbDkpun/n+7P746ZvjO5f/O9zovuHTnowun/7Q9n/hx+PHoju7zt9dHR/1TH/Et0fFV0H4P8tAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauC2gy6MPrBk62vR/ZHbzozu77pgQXR/z4px0f2BnxwS3d+waHd0/7O/2RHdP/boA6P7T23ZFN0f/+2XovsfmXBrdP/sr/5ZdP/eV2ZH9w/asTK6/3dn3hHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGjpu0PvrAaUd9Nbo/59v7R/dXfPT16P6UxXdF96/9yZej+7PGjI3uTz5hTnR/+/rvRvcXPfqn0f2xSz8Z3b/phvdE90c/eGB0/8bDT4zuj7v1zej+HSOro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODtN6+IPvDqZ6dE93/91AnR/Q/MmBrdP3/Otuj+D6Y8EN2f9vK66P7RUy6P7s9fuym6f+ei90X3t084Jbp/9yOzo/vr73syun/qosHo/rzJ2e9z900ro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1OAxr2yLPnD3fdn9O67fEd2f+XR2f/8PrYvuL3vqyOj+vEPeHd3fu+yfovsLd94R3Z8x/EZ0/9NX3RTd/+at2f0xbz4X3T/s1N9E999656nR/Y037IruuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFIDE8ctjz5w5z+/Lbp/zfqR6P7Qe0+P7q/50vjo/r2PTIzuT/v8tOj+jDcXRPf3/Hp1dP+vBt4R3Z82cU50/ztX7Y3ubzr309H9w6+7LLq/e8GR0f1vbZoe3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBjfu87HoA0Pv/Ux0/+qz3hLdH7XkHdH9kXcdEt3/4XdGovuPvvBQdP/r478V3T9y3IvR/T8azv7+zz92WHT/2WcmRfePeH5bdP99z30/ur/mmpej+7sP/HF03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQa2LpyXfSBl65cFd2/aPjs6P7Uc74Z3T/mR1Oi+0dMeSi6f9fHj43uz3/iyej+ppO3RPfPXzs5uv/OHT+N7n/vzCXR/U+svTq6v2Pz6uj+mI0fi+6fueSc6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNTDrH78WfeDCgxdE99/9+V3R/UuvvCS6/8zFy6P7t+wdE91f/cnd0f1rD/1AdH/Pbdnf5xML74ru//Xy26L7v3vhwuj+JcfuF90/+PrZ0f3lp8yM7v/isI3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq4LThE6MPLDz/V9H9j3/jxej+ocveGt3/wyevie5PeOK46P6lKyZH93/56sro/tvfmBDdX/N7P4vuD+18PLo/bvF50f17Zj0a3Z/1n38f3X96v6nR/dO2vhHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGPzx2JPrA/Ou2RffPWPTR6P7ru38V3V/4jVui+8dNHx3df+L+mdH92Tsfi+7PvfL16P6MvZdF9y945+zo/iVfnBzdHxo3K7r/86ueju7/wz2/je7/x9z9ovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MDvfjQm+sBJJwxF9y876aXo/ocuXhrdv+SeA6L7Bzz4hej+qEnTo/uPLzkpuj//l3dF9z949dro/s/ePzq6v++ys6L7B6/Kfv+P/M3Y6P6e8zZH9z917p9H910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgc1n3Rx94NnzXo3uH/XDedH9BRtujO6P/e+jo/svPLctun/p1vui+9dfND+6f9RXXovuH3vvK9H9Ux6bGd2/dviU6P7N3zsjun/g5adG9+f+1x9E94eGl0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmBc2aOjz5w7nWfiu7//s/vju5PnHV8dP/ky1ZE949f/LXo/hHDZ0f3b5x6cHT/mefXRfc3HPR4dH/x1H+N7k9c+m/R/cP/58Xo/txlX4/uP7x9JLp/+4lrovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODI226IPrDljHnR/THjn43u37jhi9H9TX+yIbp/+dL/je5/8LCh6P6CP74iuv+D09dG92844CvR/RnzPhzdP2/U30b3R12/NLp/xcT9o/tn7bw7uv/wRUdG910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpwb+cNTr6wIW//Yvo/tQrvhTdP2BoOLo/4T3HRPe/MHFXdP+MlVui+y+/PTq/z/dHXRDd/8j0t0T3L914eHT/4gXrovsnT3ogun//qIXR/VWfWx3d/+nce6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNT/BQAA///p93i/jBjU7AAAAABJRU5ErkJggg==",
            'fototype' => 'png',
            'estado' => 0,
            'email' => "operario_mercado@hotmail.com",
            'password' => bcrypt('12345678'),
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('users')->insert([
            'cedula' => '0415773774',
            'name' => 'juan',
            'current_team_id' => 8,
            'nombres' => "Juan Marcos",
            'apellidos' => "Real Villa",
            'telefono' => "095265755",
            'codigo' => "001",
            'estado' => 0,
            'direccion' => "Quito",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXj9cWdH3GcZ96DBV1HOg4McVSXJqwinmUw9KjpYVH8UdkSWysOWqWds6wKaJlC6V1UkxUNl0egc2sGGAzQAJaKJXNnC5RbJBgPWM6oWNTE5KY+yuuczrner3+gOt7n/M89/0+n8Fbvn7ofkmb7noouv+VueOi+3tW7h/dP+R7p0f3r7zu09H9+05eE91/fP7o6P7Qnw1E998zdHt0f2C/MdH9yx4ZG90/+6obovs3jbwwur/tE38T3Z974ebo/hui6wD8zhIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGd/37UPSB6760Obo/Yue+6P53H7o4un/VBUui+9c9OCm6v+Mvs5//zOcPie6vmHZ3dP8H678d3R+/YmR0/6OfOSm6/8RpH4ruTztlXnR/8+px0f3dL3w/uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDR7+rWeiD0x8YF50/8izPx7d370928gpM56M7s9aPDO6/5lV343uf2rvj6L79/9sZXT/LSNnRPfX/se06P64XZ+I7u8358jo/E2vPR3d3/LSZdH933/TO6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTg9qk/jz5w8HO7o/uXrJse3f/Zf42P7n/5nlOj+y9NPi+6/+z6udH9qSdviO5P+fwvovvnjFgV3Z9w3LTo/vcmDo/uf/2xtdH9yUctjO6vPONfovuXLtkS3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBi+5Zf/oA5dt+O/o/sa7vxndXzl9RnT//M/9KLq/7tfTo/uTVvxfdP/iE4+P7i884IDo/uzbF0f3jxk+PLr/0IKh6P7btp4b3T9h1Kej+8uemhnd//mLV0X3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmBkW+4OfrA05/dEd3fceum6P4Tj58d3R+7aVl0/+y5v4zu/3LqFdH9DQuuju7/5sLV0f13TXwwuv/oyFnR/TOWPxHdf9+w0dH9Y7/4x9H9qbs3Rvff/PKx0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauDl0X8afeCwf1sc3T9i4Z9H9w8+8/Xo/rjT74/uv3b5luj+A0Ozo/vfmX5kdH/1I8Oj+x8471vR/QOePym6P+Xaj0X3b9v5F9H9BRvPiO7v9/Bx0fnxL7wa3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBo5e+Q/RB45YfHt0/+Mzt0X3JwwcF92/Y8tQdP+uNfOi+4+ddUp0/73Ltkf3fzDs3uj+unO3RvfPWXZodH/yBW+L7v96zvjo/uQ5V0b3D174sej+c9MnRvddAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAqcF3rr05+sDlY74Y3f/OAddG9//+s6dG908bmB/d37BrbnZ/2szo/to3r47ubz3rp9H9+bMeiO7/5pOTo/vPjropur9i6OTo/t13Hhvd//41r0T3vzzvmOi+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDV40FvfHn3gzoP+Kbo/e+8bo/sXfWpedH/JjlOi+/984pTo/vlTL4nuv/H816L7Bw4eEd3fvmt+dH/8R/46uv9Hh/0wur/xX7O/Py/tvS26P3z030X333n4nOi+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDXw0xPeFX3g0TUnRfePn7J/dP/6sdlGnvaLL0X31500LLr/3qM2Rfffcsf10f23nr4ouv+Va38c3f/xgQ9H9/e8vCe6P2HZjOj+Kd9YEN0fMWNsdP/VhZdG910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgccf+0b0gTVfuzS6P/viMdH9iRfMie7/6qkno/u75nwhun/uxNnR/ZVP/yS6P/qKr0b3b/7PY6P7cxZMi+5vXXNVdH/nJ4+J7t971kej+8/fsC+6v/9p2f8fFwBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUGrgw0uvjj7w1I0HRfdvmbovuv/6+Muj+6OWbo3uT3r7muj+gy/+Nrp/z6XviO5/4U3XR/f/55wzovvv+dv10f2l9/9edH/mtz8U3b/hJ1+L7h+3dER0/+AfZr+/LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTA0VvHRB84dNs3o/u37jk0uj/qxYui+2e+f1R0/8bN66L7z/3vPdH9cc/8VXR/2avro/v73jcyuj/63b+K7k9aNDu6f/R9I6L7N9361ej+wKnHRPeHXX1CdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGnjlsH+MPnDHlYui+6df9O7o/pFjD4zu33fn8uj+4ZvHRPfv+uA10f2P/PbR6P55yxdG968bn/37Tj7x3uj+UUPzo/sTrpgW3T9i1rbo/m0f3BTdf/YPsp/fBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBqYtPz90Qc+N/fh6P6HV10T3T9k3Qei+384+EJ0f8LKC6L7w0YfH91f8+Qr0f1Hzl8S3d971Kro/rKds6L7ExYNi+4Pjrwxuj9pU/b3YdLcbdH9zz/zJ9F9FwBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUOr/AwAA//8jCnp9GwDK+AAAAABJRU5ErkJggg==",
            'fototype' => 'png',
            'email' => "usuario1@hotmail.com",
            'password' => bcrypt('12345678'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('users')->insert([
            'cedula' => '1005577369',
            'name' => 'juan',
            'current_team_id' => 8,
            'nombres' => "Joel Milla",
            'apellidos' => "Marroquin Lucero",
            'telefono' => "0854525524",
            'direccion' => "Quito",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANIUlEQVR4nOzXj9fXdX3G8W64TXElNH+kNdfaJt44LNIMsfLHWTUyvZ1OWlNvy1syB9WKNMOzTUs7I7UFNkVmoh1NPWsx3Zm6TVEKwjm1Gls4kCGQSDo9eNNBQjxsf8V1Tudcj8cfcL3v8zn3Oc/va/CFW198XdKKGXOi+9987rjo/uML9kT3J37jF9H9M3f9R3T/68/dFN3/szNGo/u/+xero/unb7s4un/Mruej+384+Y+j+4/MnRDdXxf++3/9jgXR/asemB/dHxddB+BXlgAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDW4ZvXM6AO3PH5OdH/09i9F93/21zuj+wtmnx/dn758e3T//asujO6/9uKU6P6Tt4xG96+b/WR0/5PTT4ruf3famuj+o2+YGN2f+t9PRfc/M/8r0f3rXh4f3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBoZOPij6wBOTR6P7l713a3R/9DPD0f01Jz8c3Z/9k6XR/c3njUX3lx18bXR/99GPRPeHV1wT3V/wg6Oj+we8+dLo/uv/aHN0f8LWQ6P7R5z059H94Ud/LbrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg0MP3NC9oWpr0Tnrzzoruj+7WtPje5fsfea6P5ZCw+L7l/8xP3R/RVrF0X3b3/3pOj+d6+6Obp/9/XHRveXfeF/o/tnvfGr0f1tL70+un/X6SdF91839x3ReRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq4PDL90YfuGDT9Oj+FZeOj+5v2z0/un/Epvuj+zefPBLdH/7apuj+uPPeG93fsv9/Rve/9Nlbo/uvfX1idH/rY78f3V/64b+P7h8wb050/8aNQ9H9085/LLrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg1MvPG26ANzx0ai+1vWLYzur//np6L7G+49KLo/8aYXovsfOu8b0f1tL18a3T/uluz3n/fAg9H95Qv2je7fdOP7o/sbPpL9//y9b26M7i+evS26/56fPRPddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGP3rQlOgDO/Yfiu4vXHt1dP9/HvxcdP+2g0+I7k9Z+/no/m9t3Te6f+uah6P7H3x1TXR/bML50f1xsxZF9zcsej66/6OLZkb3n7nhwej+Yw+tju6fMOnt0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQamDXqrdFH7j7nc9G94/697Ho/jsPnhvdXzr1b6L701deH90f3fOW6P60MxZE979/1dei+yML3xTdv3vLf0X3d1xyRHT/gJUXRPfveOtodH/HF2ZE92fMuzm67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNfHn596IPLL9kWXT//ss3Rvcv/cdHo/uLh/eP7g/d+K3o/imHHB/dv2fkzdH9Pb/4ZXT/tqfPju4vWjEa3X/kyFui+yfvHI7u7zd0XHR/y7hF0f1zNv9ddN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGrjzT6+NPrDuQ1uj+28a2Rbdf8Opn47ur3w++30evuqT0f1r9ntHdH/okqHo/jHfuTq6/+y+C6P7o8ffG92/a+O+0f0rTxkf3V/10+Oj+7OXnxjdn/jkA9F9FwBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUGpw7MXF0QfOfPyL0f2PHXltdH/e3NOi+3e/9O3o/ob1d0T3P73plOj+x5++Ibr/4yeXRPcfGv+R6P7VHzg6ur/4rU9F9/e7c1t0f/s190X3D5y0Lro/NO2X0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQavC0rXujDwyfOSW6//MPT4/uf2Dqn0T3Vzzx9uj+4e8ajO7vve9j0f1/OvIr0f23nTshuv/T7zwW3X/psB9G92fNHInuX/bQhdH9EyfPiu7/y7evi+4/u3tXdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGty+cnL0gQuWbIzuvzBzQnT/lHnLovt/+eVV0f19pk2K7n9u5hnR/RumZn+jLFk2I7p/+OVTovtnz7owur9sbGV0f9H6r0b3R47/RHT/3O2HRPdPX/Ku6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNXDR9R+PPjC2Z3p0/7LPnx7dn3Ho6uj+rd/fHN1ftfl3ovtnnfCD6P49974lun/Umuz3P+Bbr0T3f3vsE9H913acE93fOufR6P76ZXOi+8c+vDS6v/aifaL7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTA6L8ujj5wzz8cE93/4LuPiu7//H3PRfcPvPPA6P4VF0+O7p/6mw9E9/9v6ZHR/WPnXx7dv/CyK6P7585ZEd3feMM+0f33TftodP/QQ7ZH988ed310f2z396L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTgpEf+KvrAEbM+Fd2/7/6B6P7OC34Y3f+3w5ZE9195z8vR/aenz4/uv/Gsq6P7T43/2+j+2tv3j+7/6LMj0f0Tt/xGdP/H8+dF9xd/8Q+i+zt/siu6/+qnVkf3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKn/DwAA///2zIdaQmcd2QAAAABJRU5ErkJggg==",
            'fototype' => 'png',
            'email' => "usuario2@hotmail.com",
            'password' => bcrypt('12345678'),
            'codigo' => "002",
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);


        DB::table('users')->insert([
            'cedula' => '1005576969',
            'name' => 'juan',
            'current_team_id' => 8,
            'nombres' => "Manuel Morelo",
            'apellidos' => "Sander Aldaz",
            'telefono' => "095265755",
            'direccion' => "Pimampiro",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANIElEQVR4nOzXjdcWdH3HcW68TzB1mkMn83FG+Zw7aC5MRaMw9JgJoTuBZ5aSTcQ5p7vdNJ/mQ5ZrobYyCYQEY6uhLc6YuIQeQGorPMAAaeK21gLqWIshqLDtr/ic0zmf1+sP+PzgOvd13td3cPTUzwxLOnnp+uj+839yVnT/mTMmRff/8p7sv3/Nlqei+089fll0/6NThqL7Q5MviO5fPvGk6P7rl8+O7j/wa5dE95c/MSa6f9mZU6P7x026O7p/4dQro/vDo+sA/MoSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBucMnhp94CsnTonuH7bgwej+p74zIrq//0WvRvff+dhPo/sb134vur/gzSui+zu/NzW6v3v43dH9d//kb6L7U+89PLp/x73Z79dHn58e3X/7q/8R3R/2xB9E510AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpwSmzl0UfeNOBp0T3H9/x39H9FVtPj+6/9sTm6P4Ldx4c3R932mXR/cmjfy+6/9Lbj4vuH7j3Q9H92/5weXT/vePfiO6/f+GE6P7gxedF9z/xob+N7n/5oe3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqYNXLr0UfWHPtiOj+1q9Pie5/8+/Oje7vOWW/6P66h1+I7j/7jTHR/fO2LYvuL5x9UHT/+qH3RffvHj4qur/m9ndF968fOS66f+yKf4jub3h8Y3R/8ZyvRfddAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAqYEHz90RfeAv/mlndH/G3F9G9395/qPR/U/PnR7dH3XD96P7a8deEt1feP+U6P5Ptg1F9z+47Izo/unLLojun/zW+dH9V94yLbp/y6iJ0f2VrzwZ3f/Ye74Q3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBkatOiz6wBX3jYnuL996QHT/uj03RvePvuUD0f3jTv5WdH/a7Y9E9yd996ro/h1PLo/uP3fFYHT/nD+/M7q/+Z2zovv33DUjur9q1ujo/jEPrI/uf/eQM6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTg6Vv+PvrArrlbo/tLtzwc3d+288jo/uDUa6P7pzy0ILr/8vH7ovubjsr+fZ74wVnR/Q2TvhPd/+yG46P7n9zzx9H9A468Lrp/9Kbt0f37/2hmdP+QkSdE910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpwYEn74o+sOjdh0f3r1j51ej+V559LLp/xBE/iO5fePGM6P64H74vuj/85rXR/bXv2hfdP/rBs6L7Zx/xzej+Gf+5KLp/9fnzovtTJ2U//3mXjI3uz3/uf6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTAL1YeEX3gpRHR+WEjrn0quj93KPsfuHj8+Oj+uC/cHt3/9uszo/v7/d+06P6/nPqn0f3dZ98T3R+6e2N0/9zLPhndX/a26PywkT/I/sY96Itfje7vOmFldN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGrz5/DdHH7jpX4+J7n942rTo/qUnHRTdn/hnr0T3r3vspej+774xObq/5Lbbo/vzN2Q//4N/fmd0f/fnfye6f+GKHdH9s5fdGt1/aOx50f0J3x8T3X9x5wvRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqYPtvfTn6wDXveCS6f8Kbbojub57xG9H9O//n1ej+0qVLovuf2nhddP/FxTOj+/vf8nR0f/q88dH9Hy06MLp/9fxTo/sfOeqq6P4xv/+P0f1/v+by6P437npLdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGrj0lJ9FH5j9pQui+zft/kV0/8YFH4vuX7T8r6L7e9ecE90/9NMPRPfn/fb26P63bl0c3b96xaHR/XWn/XV0f/GEidH9f9t1a3T/or3HRvc/c1/2+zvhvndE910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgRvXro8+cPy3r4zuT1rxtej+vkWPRvd/OHNzdP/GKTOi+5d+eFt0/+SPfym6/9xJ+0f3r1y1Ibr/8V0/ju7vOeb16P6m/Q6L7j86+eHo/lljVkb3d5/5uei+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDWwafVHog8sfNvPo/u3/vOM6P7YYeuj+7++fWV0/4vDR0b3v37G/dH9zx0+M7o/7+nB6P4hB9wb3Z8wakt0f8dp50f359371uj+uhMOje4PvDghun/T049E910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgbN+ujf6wKwTL4juH/XswdH9cR84Mro/+/3PRPd3vuex6P5t14yK7q/5/Jzo/vOT74/u3/HMUHT/oROXRPd3jMz+RvzZspej+ycdOT26P376j6P7K25eF913AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQZ+c8n10Qf2bXpvdP/6cauj++tWj47uH/vZa6L7s44aiu7PeWBfdH/x0k9E9+fOuyq6v3v1DdH9s0eMje6P/q/s/o9umxLdnz7xjej+6hseie6vWXhOdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACU+v8AAAD//w04eOm/l5puAAAAAElFTkSuQmCC",
            'fototype' => 'png',
            'email' => "usuario3@hotmail.com",
            'password' => bcrypt('12345678'),
            'codigo' => "003",
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('users')->insert([
            'cedula' => '1088557769',
            'name' => 'juan',
            'current_team_id' => 8,
            'nombres' => "Carlos Marcel",
            'apellidos' => "Quilo Luvir",
            'telefono' => "095265755",
            'direccion' => "Pimampiro",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANIElEQVR4nOzXi6/Q9X3GcY4cdUVW473trDpqpTpAXB216uzQg9hYjBjnBaWtNxzTNZ1u1RWxhFpba2uTzVrmbOfmRE3jZXOlA+nVNRBFBIW0MCsrBLYKZ1QuKWeydn/FkzR5Xq8/4PkmJ79z3uczOG7Nk6OSTlr+vej+0Ol/Gd2/4q82R/dHXXBhdH70xzZE9/fdvDe6v3H//0X35z38cnT/z+aPi+5f+47jovtTXzwnun/+Bfuj+0uWXRvdv+m+NdH9bYvHR/cPiK4D8BtLAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGnxm3oToAyf+4eei+wdOWhLdH33oSHT/xF0zo/sf+reDovt3HLMpuv/Ry2+J7t932iXR/T1PHx3dH7nrtOj+qzecEt1/38Lfju5f9MTG6P6xF+6N7v9s7HXRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqYMW6z0UfOO2SLdH9lcNzovt/d+/vR/eH1z4Z3V9y/4zo/hEP/X10f90/bI3uX/PaTdH9Gd/ZHt3/m+89Gt1/enP293fpAVOj+7/z7gnR/X3f/2F0/+ipp0b3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmB1ds+GX1gZM2i6P6SQ98V3d919/7o/o0ffiy6/4mVK6P7x2w8L7q/4Kxd0f3J8xZH9y+fcWl0f3jyIdH9Exc+G90//rHs35/X582O7i8+4rDo/v0v/E903wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQamDw0OfrAxed8NLr/+a9Miu7Pf+7I6P7bHj84un/nqSdG939w2RHR/UvGLI3uv3n3u6P7U46+M7q/6ITbovuP3Lo+uj/83ROi+x97Ymp0/8pH50f3fz5qQXTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBr89juvjz6w4flt0f01M+ZG9y8dPT26/+Km26L7B427K7p/2ZE3RPe/PCb7fd592bPR/ZPuOSe6f9S+xdH9vTsPju4fN2lVdH/TPW+L7h88777o/u4/+JfovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg1sPyK90Uf+M5DT0b3vz5nRnR/7Ud+Fd0fOfXw6P4bQ7Oj++t2XRTdP/yBudH9nXf8ILp/xEV7o/tPbbojuv/Gqw9E93fcuiO6/9Cq7M9/+NOTo/u3Tzsjuu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDSxZdHb0gTWnXBfdP/v4o6P7ow6cFp3/j2//JLo/sH56dH/RfQ9G9z/whZ9F94/86mB0f9SxS6Pzn3nmT6P7H3rpS9H9Wyf8Mrr/2XsXR/ef+fU3ovvv+a1HovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1OCsr382+sCE5V+O7m+8fU50f8Mj74/ubz/hyuj+vl/OjO5vWp79H2LK6tHR/a/N/nl0f9LQ/uj+1d96b3R//JgbovtzN2S//2dfOjS6f+cHfhTdXzvpoei+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDWw8OkHow+MG39UdP/z4+6M7i9fck10f9bod0b3f3TYn0f3v7/wG9H97X/8ZHR/6KSXo/s3P/7j6P6hV/00un/yG+dG92dfuDu6/+Hvzo/uvzxxc3T/nrvHR/ddAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAqcE73ro3+sBnRn8xuj/h3r3R/elPfDy6/5FtW6L7W986K7q/7sxDovs379se3d87siC6/6urx0X3p2+5Lbq//vmR6P6Ncy6O7v907J7o/p+M3hjd/+S/nx/ddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGFz38XPSBu47dHd0/eeH66P47Xr8lun/5im9G9ycs2hPdP2P+juj+Tf96e3R/51X/Fd3/+MT50f0Dx54b3f/KzPOj+y+OWRbdX/bDL0X3rx94Krr//NfejO67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgPHnDE2+sArK2dE9//28cui+9sXfCu6Pzz7vOj+qJfeH51/bemK6P4tE8dE969/dEt0/8Kn3xXdn37F49H9zbfcFN3/xcS10f0b3/5odH/jvoej+1cfvy267wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNnH7GgugDs85eFt3fcPDm6P4Xrzgquv/KlJHo/g2r3ozuH3bp1uj+U6dvie4P3X5mdP+vfzEc3b/uv3dE99+a9sHo/prjpkT3hy59Lrr/7O7/je5P++dTovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODJP9kcfWDsrtXR/b94+9zo/qdGXRXdn7L7wej+B987M7p/yAEXR/c/9etro/uzRqZF9+e+cGZ0/4IvvJbdP/f3ovvXHP670f3r73khuv+eV66L7s99YEV03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQauPLV9dEHzhq6K7o/NHxedP+wJcPR/df/aGp0/7x5O6P793/6P6P7j83ZFt3/8TlHRvdXf2JPdP+fVn0zuj/r4X+M7t84f2Z0f/Wmg6L7W8d/Nbo/8eS50X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQ6v8DAAD//446gmuVjy8uAAAAAElFTkSuQmCC",
            'fototype' => 'png',
            'email' => "usuario4@hotmail.com",
            'password' => bcrypt('12345678'),
            'codigo' => "004",
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('users')->insert([
            'cedula' => '0400730701',
            'name' => 'C0400730701',
            'current_team_id' => 9,
            'nombres' => "Biden Roberto",
            'apellidos' => "Parlevou Boubie",
            'telefono' => "095265755",
            'direccion' => "Atuntaqui",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANIElEQVR4nOzXi6/Q9X3GcY4cdUVW473trDpqpTpAXB216uzQg9hYjBjnBaWtNxzTNZ1u1RWxhFpba2uTzVrmbOfmRE3jZXOlA+nVNRBFBIW0MCsrBLYKZ1QuKWeydn/FkzR5Xq8/4PkmJ79z3uczOG7Nk6OSTlr+vej+0Ol/Gd2/4q82R/dHXXBhdH70xzZE9/fdvDe6v3H//0X35z38cnT/z+aPi+5f+47jovtTXzwnun/+Bfuj+0uWXRvdv+m+NdH9bYvHR/cPiK4D8BtLAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGnxm3oToAyf+4eei+wdOWhLdH33oSHT/xF0zo/sf+reDovt3HLMpuv/Ry2+J7t932iXR/T1PHx3dH7nrtOj+qzecEt1/38Lfju5f9MTG6P6xF+6N7v9s7HXRfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqYMW6z0UfOO2SLdH9lcNzovt/d+/vR/eH1z4Z3V9y/4zo/hEP/X10f90/bI3uX/PaTdH9Gd/ZHt3/m+89Gt1/enP293fpAVOj+7/z7gnR/X3f/2F0/+ipp0b3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmB1ds+GX1gZM2i6P6SQ98V3d919/7o/o0ffiy6/4mVK6P7x2w8L7q/4Kxd0f3J8xZH9y+fcWl0f3jyIdH9Exc+G90//rHs35/X582O7i8+4rDo/v0v/E903wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQamDw0OfrAxed8NLr/+a9Miu7Pf+7I6P7bHj84un/nqSdG939w2RHR/UvGLI3uv3n3u6P7U46+M7q/6ITbovuP3Lo+uj/83ROi+x97Ymp0/8pH50f3fz5qQXTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBr89juvjz6w4flt0f01M+ZG9y8dPT26/+Km26L7B427K7p/2ZE3RPe/PCb7fd592bPR/ZPuOSe6f9S+xdH9vTsPju4fN2lVdH/TPW+L7h88777o/u4/+JfovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg1sPyK90Uf+M5DT0b3vz5nRnR/7Ud+Fd0fOfXw6P4bQ7Oj++t2XRTdP/yBudH9nXf8ILp/xEV7o/tPbbojuv/Gqw9E93fcuiO6/9Cq7M9/+NOTo/u3Tzsjuu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDSxZdHb0gTWnXBfdP/v4o6P7ow6cFp3/j2//JLo/sH56dH/RfQ9G9z/whZ9F94/86mB0f9SxS6Pzn3nmT6P7H3rpS9H9Wyf8Mrr/2XsXR/ef+fU3ovvv+a1HovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1OCsr382+sCE5V+O7m+8fU50f8Mj74/ubz/hyuj+vl/OjO5vWp79H2LK6tHR/a/N/nl0f9LQ/uj+1d96b3R//JgbovtzN2S//2dfOjS6f+cHfhTdXzvpoei+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDWw8OkHow+MG39UdP/z4+6M7i9fck10f9bod0b3f3TYn0f3v7/wG9H97X/8ZHR/6KSXo/s3P/7j6P6hV/00un/yG+dG92dfuDu6/+Hvzo/uvzxxc3T/nrvHR/ddAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAqcE73ro3+sBnRn8xuj/h3r3R/elPfDy6/5FtW6L7W986K7q/7sxDovs379se3d87siC6/6urx0X3p2+5Lbq//vmR6P6Ncy6O7v907J7o/p+M3hjd/+S/nx/ddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGFz38XPSBu47dHd0/eeH66P47Xr8lun/5im9G9ycs2hPdP2P+juj+Tf96e3R/51X/Fd3/+MT50f0Dx54b3f/KzPOj+y+OWRbdX/bDL0X3rx94Krr//NfejO67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgPHnDE2+sArK2dE9//28cui+9sXfCu6Pzz7vOj+qJfeH51/bemK6P4tE8dE969/dEt0/8Kn3xXdn37F49H9zbfcFN3/xcS10f0b3/5odH/jvoej+1cfvy267wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNnH7GgugDs85eFt3fcPDm6P4Xrzgquv/KlJHo/g2r3ozuH3bp1uj+U6dvie4P3X5mdP+vfzEc3b/uv3dE99+a9sHo/prjpkT3hy59Lrr/7O7/je5P++dTovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODJP9kcfWDsrtXR/b94+9zo/qdGXRXdn7L7wej+B987M7p/yAEXR/c/9etro/uzRqZF9+e+cGZ0/4IvvJbdP/f3ovvXHP670f3r73khuv+eV66L7s99YEV03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQauPLV9dEHzhq6K7o/NHxedP+wJcPR/df/aGp0/7x5O6P793/6P6P7j83ZFt3/8TlHRvdXf2JPdP+fVn0zuj/r4X+M7t84f2Z0f/Wmg6L7W8d/Nbo/8eS50X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQ6v8DAAD//446gmuVjy8uAAAAAElFTkSuQmCC",
            'fototype' => 'png',
            'codigo'=>'PSEP-5',
            'email' => "veterinario@hotmail.com",
            'password' => bcrypt('12345678'),
            'estado' => 0,
          //  'created_at' => Carbon::now(),
          //  'updated_at' => Carbon::now(),
          'created_at' => '2021-01-04 11:14:57',
          'created_at' => '2021-01-04 11:14:57',
        ]);
        DB::table('users')->insert([
            'cedula' => '1005577382',
            'name' => 'juan',
            'current_team_id' => 10,
            'nombres' => "Carlos Alejandro",
            'apellidos' => "Paredes Fuentes",
            'telefono' => "095265755",
            'direccion' => "Quito",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXi6/fdX3HcU57mFTZmNzSOooMLTIQBE4hXMpldbhpuWxokbIKiiU4OT1SoWDDgK1MHShjRWiVpCUUaCM6B7Wo1VIVsJcAKbJ1WCibhbXFxpqVKh1NNfsrXsmS1+PxB7w+yS/f/J55D97yrl37JH3uy/dH939x+ubo/ujPHBTdP377tOj+3teOi+4/vO93o/sPbDkpun/n+7P746ZvjO5f/O9zovuHTnowun/7Q9n/hx+PHoju7zt9dHR/1TH/Et0fFV0H4P8tAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauC2gy6MPrBk62vR/ZHbzozu77pgQXR/z4px0f2BnxwS3d+waHd0/7O/2RHdP/boA6P7T23ZFN0f/+2XovsfmXBrdP/sr/5ZdP/eV2ZH9w/asTK6/3dn3hHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGjpu0PvrAaUd9Nbo/59v7R/dXfPT16P6UxXdF96/9yZej+7PGjI3uTz5hTnR/+/rvRvcXPfqn0f2xSz8Z3b/phvdE90c/eGB0/8bDT4zuj7v1zej+HSOro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODtN6+IPvDqZ6dE93/91AnR/Q/MmBrdP3/Otuj+D6Y8EN2f9vK66P7RUy6P7s9fuym6f+ei90X3t084Jbp/9yOzo/vr73syun/qosHo/rzJ2e9z900ro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1OAxr2yLPnD3fdn9O67fEd2f+XR2f/8PrYvuL3vqyOj+vEPeHd3fu+yfovsLd94R3Z8x/EZ0/9NX3RTd/+at2f0xbz4X3T/s1N9E999656nR/Y037IruuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFIDE8ctjz5w5z+/Lbp/zfqR6P7Qe0+P7q/50vjo/r2PTIzuT/v8tOj+jDcXRPf3/Hp1dP+vBt4R3Z82cU50/ztX7Y3ubzr309H9w6+7LLq/e8GR0f1vbZoe3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBjfu87HoA0Pv/Ux0/+qz3hLdH7XkHdH9kXcdEt3/4XdGovuPvvBQdP/r478V3T9y3IvR/T8azv7+zz92WHT/2WcmRfePeH5bdP99z30/ur/mmpej+7sP/HF03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQa2LpyXfSBl65cFd2/aPjs6P7Uc74Z3T/mR1Oi+0dMeSi6f9fHj43uz3/iyej+ppO3RPfPXzs5uv/OHT+N7n/vzCXR/U+svTq6v2Pz6uj+mI0fi+6fueSc6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNTDrH78WfeDCgxdE99/9+V3R/UuvvCS6/8zFy6P7t+wdE91f/cnd0f1rD/1AdH/Pbdnf5xML74ru//Xy26L7v3vhwuj+JcfuF90/+PrZ0f3lp8yM7v/isI3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq4LThE6MPLDz/V9H9j3/jxej+ocveGt3/wyevie5PeOK46P6lKyZH93/56sro/tvfmBDdX/N7P4vuD+18PLo/bvF50f17Zj0a3Z/1n38f3X96v6nR/dO2vhHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGPzx2JPrA/Ou2RffPWPTR6P7ru38V3V/4jVui+8dNHx3df+L+mdH92Tsfi+7PvfL16P6MvZdF9y945+zo/iVfnBzdHxo3K7r/86ueju7/wz2/je7/x9z9ovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MDvfjQm+sBJJwxF9y876aXo/ocuXhrdv+SeA6L7Bzz4hej+qEnTo/uPLzkpuj//l3dF9z949dro/s/ePzq6v++ys6L7B6/Kfv+P/M3Y6P6e8zZH9z917p9H910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgc1n3Rx94NnzXo3uH/XDedH9BRtujO6P/e+jo/svPLctun/p1vui+9dfND+6f9RXXovuH3vvK9H9Ux6bGd2/dviU6P7N3zsjun/g5adG9+f+1x9E94eGl0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmBc2aOjz5w7nWfiu7//s/vju5PnHV8dP/ky1ZE949f/LXo/hHDZ0f3b5x6cHT/mefXRfc3HPR4dH/x1H+N7k9c+m/R/cP/58Xo/txlX4/uP7x9JLp/+4lrovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODI226IPrDljHnR/THjn43u37jhi9H9TX+yIbp/+dL/je5/8LCh6P6CP74iuv+D09dG92844CvR/RnzPhzdP2/U30b3R12/NLp/xcT9o/tn7bw7uv/wRUdG910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpwb+cNTr6wIW//Yvo/tQrvhTdP2BoOLo/4T3HRPe/MHFXdP+MlVui+y+/PTq/z/dHXRDd/8j0t0T3L914eHT/4gXrovsnT3ogun//qIXR/VWfWx3d/+nce6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNT/BQAA///p93i/jBjU7AAAAABJRU5ErkJggg==",
            'fototype' => 'png',
            'email' => "usuario_mercado@hotmail.com",
            'password' => bcrypt('12345678'),
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('users')->insert([
            'cedula' => '0454323456',
            'name' => 'juan',
            'current_team_id' => 10,
            'nombres' => "Carol Melissa",
            'apellidos' => "Lóopez Aguirre",
            'telefono' => "095265755",
            'direccion' => "Quito",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXi6/fdX3HcU57mFTZmNzSOooMLTIQBE4hXMpldbhpuWxokbIKiiU4OT1SoWDDgK1MHShjRWiVpCUUaCM6B7Wo1VIVsJcAKbJ1WCibhbXFxpqVKh1NNfsrXsmS1+PxB7w+yS/f/J55D97yrl37JH3uy/dH939x+ubo/ujPHBTdP377tOj+3teOi+4/vO93o/sPbDkpun/n+7P746ZvjO5f/O9zovuHTnowun/7Q9n/hx+PHoju7zt9dHR/1TH/Et0fFV0H4P8tAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauC2gy6MPrBk62vR/ZHbzozu77pgQXR/z4px0f2BnxwS3d+waHd0/7O/2RHdP/boA6P7T23ZFN0f/+2XovsfmXBrdP/sr/5ZdP/eV2ZH9w/asTK6/3dn3hHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGjpu0PvrAaUd9Nbo/59v7R/dXfPT16P6UxXdF96/9yZej+7PGjI3uTz5hTnR/+/rvRvcXPfqn0f2xSz8Z3b/phvdE90c/eGB0/8bDT4zuj7v1zej+HSOro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODtN6+IPvDqZ6dE93/91AnR/Q/MmBrdP3/Otuj+D6Y8EN2f9vK66P7RUy6P7s9fuym6f+ei90X3t084Jbp/9yOzo/vr73syun/qosHo/rzJ2e9z900ro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1OAxr2yLPnD3fdn9O67fEd2f+XR2f/8PrYvuL3vqyOj+vEPeHd3fu+yfovsLd94R3Z8x/EZ0/9NX3RTd/+at2f0xbz4X3T/s1N9E999656nR/Y037IruuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFIDE8ctjz5w5z+/Lbp/zfqR6P7Qe0+P7q/50vjo/r2PTIzuT/v8tOj+jDcXRPf3/Hp1dP+vBt4R3Z82cU50/ztX7Y3ubzr309H9w6+7LLq/e8GR0f1vbZoe3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBjfu87HoA0Pv/Ux0/+qz3hLdH7XkHdH9kXcdEt3/4XdGovuPvvBQdP/r478V3T9y3IvR/T8azv7+zz92WHT/2WcmRfePeH5bdP99z30/ur/mmpej+7sP/HF03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQa2LpyXfSBl65cFd2/aPjs6P7Uc74Z3T/mR1Oi+0dMeSi6f9fHj43uz3/iyej+ppO3RPfPXzs5uv/OHT+N7n/vzCXR/U+svTq6v2Pz6uj+mI0fi+6fueSc6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNTDrH78WfeDCgxdE99/9+V3R/UuvvCS6/8zFy6P7t+wdE91f/cnd0f1rD/1AdH/Pbdnf5xML74ru//Xy26L7v3vhwuj+JcfuF90/+PrZ0f3lp8yM7v/isI3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq4LThE6MPLDz/V9H9j3/jxej+ocveGt3/wyevie5PeOK46P6lKyZH93/56sro/tvfmBDdX/N7P4vuD+18PLo/bvF50f17Zj0a3Z/1n38f3X96v6nR/dO2vhHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGPzx2JPrA/Ou2RffPWPTR6P7ru38V3V/4jVui+8dNHx3df+L+mdH92Tsfi+7PvfL16P6MvZdF9y945+zo/iVfnBzdHxo3K7r/86ueju7/wz2/je7/x9z9ovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MDvfjQm+sBJJwxF9y876aXo/ocuXhrdv+SeA6L7Bzz4hej+qEnTo/uPLzkpuj//l3dF9z949dro/s/ePzq6v++ys6L7B6/Kfv+P/M3Y6P6e8zZH9z917p9H910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgc1n3Rx94NnzXo3uH/XDedH9BRtujO6P/e+jo/svPLctun/p1vui+9dfND+6f9RXXovuH3vvK9H9Ux6bGd2/dviU6P7N3zsjun/g5adG9+f+1x9E94eGl0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmBc2aOjz5w7nWfiu7//s/vju5PnHV8dP/ky1ZE949f/LXo/hHDZ0f3b5x6cHT/mefXRfc3HPR4dH/x1H+N7k9c+m/R/cP/58Xo/txlX4/uP7x9JLp/+4lrovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODI226IPrDljHnR/THjn43u37jhi9H9TX+yIbp/+dL/je5/8LCh6P6CP74iuv+D09dG92844CvR/RnzPhzdP2/U30b3R12/NLp/xcT9o/tn7bw7uv/wRUdG910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpwb+cNTr6wIW//Yvo/tQrvhTdP2BoOLo/4T3HRPe/MHFXdP+MlVui+y+/PTq/z/dHXRDd/8j0t0T3L914eHT/4gXrovsnT3ogun//qIXR/VWfWx3d/+nce6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNT/BQAA///p93i/jBjU7AAAAABJRU5ErkJggg==",
            'fototype' => 'png',
            'email' => "usuario_mercado2@hotmail.com",
            'password' => bcrypt('12345678'),
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('users')->insert([
            'cedula' => '0890443456',
            'name' => 'juan',
            'current_team_id' => 10,
            'nombres' => "María Patricia",
            'apellidos' => "Fuentes Fuentes",
            'telefono' => "095265755",
            'direccion' => "Ibarra",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXi6/fdX3HcU57mFTZmNzSOooMLTIQBE4hXMpldbhpuWxokbIKiiU4OT1SoWDDgK1MHShjRWiVpCUUaCM6B7Wo1VIVsJcAKbJ1WCibhbXFxpqVKh1NNfsrXsmS1+PxB7w+yS/f/J55D97yrl37JH3uy/dH939x+ubo/ujPHBTdP377tOj+3teOi+4/vO93o/sPbDkpun/n+7P746ZvjO5f/O9zovuHTnowun/7Q9n/hx+PHoju7zt9dHR/1TH/Et0fFV0H4P8tAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauC2gy6MPrBk62vR/ZHbzozu77pgQXR/z4px0f2BnxwS3d+waHd0/7O/2RHdP/boA6P7T23ZFN0f/+2XovsfmXBrdP/sr/5ZdP/eV2ZH9w/asTK6/3dn3hHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGjpu0PvrAaUd9Nbo/59v7R/dXfPT16P6UxXdF96/9yZej+7PGjI3uTz5hTnR/+/rvRvcXPfqn0f2xSz8Z3b/phvdE90c/eGB0/8bDT4zuj7v1zej+HSOro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODtN6+IPvDqZ6dE93/91AnR/Q/MmBrdP3/Otuj+D6Y8EN2f9vK66P7RUy6P7s9fuym6f+ei90X3t084Jbp/9yOzo/vr73syun/qosHo/rzJ2e9z900ro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1OAxr2yLPnD3fdn9O67fEd2f+XR2f/8PrYvuL3vqyOj+vEPeHd3fu+yfovsLd94R3Z8x/EZ0/9NX3RTd/+at2f0xbz4X3T/s1N9E999656nR/Y037IruuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFIDE8ctjz5w5z+/Lbp/zfqR6P7Qe0+P7q/50vjo/r2PTIzuT/v8tOj+jDcXRPf3/Hp1dP+vBt4R3Z82cU50/ztX7Y3ubzr309H9w6+7LLq/e8GR0f1vbZoe3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBjfu87HoA0Pv/Ux0/+qz3hLdH7XkHdH9kXcdEt3/4XdGovuPvvBQdP/r478V3T9y3IvR/T8azv7+zz92WHT/2WcmRfePeH5bdP99z30/ur/mmpej+7sP/HF03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQa2LpyXfSBl65cFd2/aPjs6P7Uc74Z3T/mR1Oi+0dMeSi6f9fHj43uz3/iyej+ppO3RPfPXzs5uv/OHT+N7n/vzCXR/U+svTq6v2Pz6uj+mI0fi+6fueSc6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNTDrH78WfeDCgxdE99/9+V3R/UuvvCS6/8zFy6P7t+wdE91f/cnd0f1rD/1AdH/Pbdnf5xML74ru//Xy26L7v3vhwuj+JcfuF90/+PrZ0f3lp8yM7v/isI3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq4LThE6MPLDz/V9H9j3/jxej+ocveGt3/wyevie5PeOK46P6lKyZH93/56sro/tvfmBDdX/N7P4vuD+18PLo/bvF50f17Zj0a3Z/1n38f3X96v6nR/dO2vhHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGPzx2JPrA/Ou2RffPWPTR6P7ru38V3V/4jVui+8dNHx3df+L+mdH92Tsfi+7PvfL16P6MvZdF9y945+zo/iVfnBzdHxo3K7r/86ueju7/wz2/je7/x9z9ovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MDvfjQm+sBJJwxF9y876aXo/ocuXhrdv+SeA6L7Bzz4hej+qEnTo/uPLzkpuj//l3dF9z949dro/s/ePzq6v++ys6L7B6/Kfv+P/M3Y6P6e8zZH9z917p9H910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgc1n3Rx94NnzXo3uH/XDedH9BRtujO6P/e+jo/svPLctun/p1vui+9dfND+6f9RXXovuH3vvK9H9Ux6bGd2/dviU6P7N3zsjun/g5adG9+f+1x9E94eGl0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmBc2aOjz5w7nWfiu7//s/vju5PnHV8dP/ky1ZE949f/LXo/hHDZ0f3b5x6cHT/mefXRfc3HPR4dH/x1H+N7k9c+m/R/cP/58Xo/txlX4/uP7x9JLp/+4lrovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODI226IPrDljHnR/THjn43u37jhi9H9TX+yIbp/+dL/je5/8LCh6P6CP74iuv+D09dG92844CvR/RnzPhzdP2/U30b3R12/NLp/xcT9o/tn7bw7uv/wRUdG910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpwb+cNTr6wIW//Yvo/tQrvhTdP2BoOLo/4T3HRPe/MHFXdP+MlVui+y+/PTq/z/dHXRDd/8j0t0T3L914eHT/4gXrovsnT3ogun//qIXR/VWfWx3d/+nce6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNT/BQAA///p93i/jBjU7AAAAABJRU5ErkJggg==",
            'fototype' => 'png',
            'email' => "usuario_mercado3@hotmail.com",
            'password' => bcrypt('12345678'),
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('users')->insert([
            'cedula' => '1003742777',
            'name' => 'juan',
            'current_team_id' => 10,
            'nombres' => "Pamela Rocío",
            'apellidos' => "Córdova Estevez",
            'telefono' => "095265755",
            'direccion' => "Otavalo",
            'foto' => "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXi6/fdX3HcU57mFTZmNzSOooMLTIQBE4hXMpldbhpuWxokbIKiiU4OT1SoWDDgK1MHShjRWiVpCUUaCM6B7Wo1VIVsJcAKbJ1WCibhbXFxpqVKh1NNfsrXsmS1+PxB7w+yS/f/J55D97yrl37JH3uy/dH939x+ubo/ujPHBTdP377tOj+3teOi+4/vO93o/sPbDkpun/n+7P746ZvjO5f/O9zovuHTnowun/7Q9n/hx+PHoju7zt9dHR/1TH/Et0fFV0H4P8tAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauC2gy6MPrBk62vR/ZHbzozu77pgQXR/z4px0f2BnxwS3d+waHd0/7O/2RHdP/boA6P7T23ZFN0f/+2XovsfmXBrdP/sr/5ZdP/eV2ZH9w/asTK6/3dn3hHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGjpu0PvrAaUd9Nbo/59v7R/dXfPT16P6UxXdF96/9yZej+7PGjI3uTz5hTnR/+/rvRvcXPfqn0f2xSz8Z3b/phvdE90c/eGB0/8bDT4zuj7v1zej+HSOro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODtN6+IPvDqZ6dE93/91AnR/Q/MmBrdP3/Otuj+D6Y8EN2f9vK66P7RUy6P7s9fuym6f+ei90X3t084Jbp/9yOzo/vr73syun/qosHo/rzJ2e9z900ro/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1OAxr2yLPnD3fdn9O67fEd2f+XR2f/8PrYvuL3vqyOj+vEPeHd3fu+yfovsLd94R3Z8x/EZ0/9NX3RTd/+at2f0xbz4X3T/s1N9E999656nR/Y037IruuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFIDE8ctjz5w5z+/Lbp/zfqR6P7Qe0+P7q/50vjo/r2PTIzuT/v8tOj+jDcXRPf3/Hp1dP+vBt4R3Z82cU50/ztX7Y3ubzr309H9w6+7LLq/e8GR0f1vbZoe3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBjfu87HoA0Pv/Ux0/+qz3hLdH7XkHdH9kXcdEt3/4XdGovuPvvBQdP/r478V3T9y3IvR/T8azv7+zz92WHT/2WcmRfePeH5bdP99z30/ur/mmpej+7sP/HF03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQa2LpyXfSBl65cFd2/aPjs6P7Uc74Z3T/mR1Oi+0dMeSi6f9fHj43uz3/iyej+ppO3RPfPXzs5uv/OHT+N7n/vzCXR/U+svTq6v2Pz6uj+mI0fi+6fueSc6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNTDrH78WfeDCgxdE99/9+V3R/UuvvCS6/8zFy6P7t+wdE91f/cnd0f1rD/1AdH/Pbdnf5xML74ru//Xy26L7v3vhwuj+JcfuF90/+PrZ0f3lp8yM7v/isI3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq4LThE6MPLDz/V9H9j3/jxej+ocveGt3/wyevie5PeOK46P6lKyZH93/56sro/tvfmBDdX/N7P4vuD+18PLo/bvF50f17Zj0a3Z/1n38f3X96v6nR/dO2vhHddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGPzx2JPrA/Ou2RffPWPTR6P7ru38V3V/4jVui+8dNHx3df+L+mdH92Tsfi+7PvfL16P6MvZdF9y945+zo/iVfnBzdHxo3K7r/86ueju7/wz2/je7/x9z9ovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1MDvfjQm+sBJJwxF9y876aXo/ocuXhrdv+SeA6L7Bzz4hej+qEnTo/uPLzkpuj//l3dF9z949dro/s/ePzq6v++ys6L7B6/Kfv+P/M3Y6P6e8zZH9z917p9H910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgc1n3Rx94NnzXo3uH/XDedH9BRtujO6P/e+jo/svPLctun/p1vui+9dfND+6f9RXXovuH3vvK9H9Ux6bGd2/dviU6P7N3zsjun/g5adG9+f+1x9E94eGl0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKmBc2aOjz5w7nWfiu7//s/vju5PnHV8dP/ky1ZE949f/LXo/hHDZ0f3b5x6cHT/mefXRfc3HPR4dH/x1H+N7k9c+m/R/cP/58Xo/txlX4/uP7x9JLp/+4lrovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODI226IPrDljHnR/THjn43u37jhi9H9TX+yIbp/+dL/je5/8LCh6P6CP74iuv+D09dG92844CvR/RnzPhzdP2/U30b3R12/NLp/xcT9o/tn7bw7uv/wRUdG910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpwb+cNTr6wIW//Yvo/tQrvhTdP2BoOLo/4T3HRPe/MHFXdP+MlVui+y+/PTq/z/dHXRDd/8j0t0T3L914eHT/4gXrovsnT3ogun//qIXR/VWfWx3d/+nce6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNT/BQAA///p93i/jBjU7AAAAABJRU5ErkJggg==",
            'fototype' => 'png',
            'email' => "usuario_mercado4@hotmail.com",
            'password' => bcrypt('12345678'),
            'estado' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]); */

        DB::table('team_user')->insert([
            'team_id' => 1,
            'user_id' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

       /*   DB::table('team_user')->insert([
            'team_id' => 2,
            'user_id' => 2,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 3,
            'user_id' => 3,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 4,
            'user_id' => 4,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 5,
            'user_id' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 6,
            'user_id' => 6,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 7,
            'user_id' => 7,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 8,
            'user_id' => 8,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 8,
            'user_id' => 9,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 8,
            'user_id' => 10,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 8,
            'user_id' => 11,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('team_user')->insert([
            'team_id' => 9,
            'user_id' => 12,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('team_user')->insert([
            'team_id' => 10,
            'user_id' => 13,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('team_user')->insert([
            'team_id' => 10,
            'user_id' => 14,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('team_user')->insert([
            'team_id' => 10,
            'user_id' => 15,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('team_user')->insert([
            'team_id' => 10,
            'user_id' => 16,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);  */
    }
}
